[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "napari-stereoTis"
version = "0.1.0"
description = "Used to mask cells or tissues for spatial transcriptomes"
authors = [{name = "Qi Fang", email = "fangqi@genomics.cn"}]
readme = "README.rst"

[project.entry-points."napari.manifest"]
napari-stereoTis = "napari_stereoTis:napari.yaml"
