[project]
name = "rubberize"
version = "0.1.0"
description = "Turn Python calculations into well-formatted, math-rich documents."
authors = [
    {name = "Chito Peralta", email = "chitoangeloperalta@gmail.com"}
]
keywords = ["latex", "markdown", "jupyter", "notebook", "math", "engineering"]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "markdown>=3.7,<4.0",
    "titlecase>=2.4.1,<3.0.0"
]

[project.optional-dependencies]
notebook = [
    "ipython>=9.0.2,<10.0.0",
    "playwright>=1.51.0,<2.0.0"
]
dev = [
    "ipython>=9.0.2,<10.0.0",
    "playwright>=1.51.0,<2.0.0",
    "jupyterlab>=4.3.6,<5.0.0",
    "pint>=0.24.4,<0.25.0",
    "sympy>=1.13.3,<2.0.0",
    "numpy>=2.2.4,<3.0.0",
]

[project.urls]
repository = "https://github.com/chitoperalta/rubberize"
homepage = "https://github.com/chitoperalta/rubberize"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["rubberize"]
