[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "touhoubbbunits"
version = "0.2.0"
description = "用于直接导入东方同人作品东方大战争的兵种信息,附带一个全随机器"
readme="README.md"
authors = [
    {name = "Komeiji_HSS", email = "1271349487@qq.com"}
]
classifiers=["Programming Language :: Python :: 3.11",
"License :: OSI Approved :: MIT License"]
dependencies = ["random","tkinter"
]
requires-python = ">= 3.9"