[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "latex_generator_evgenfosgen"
version = "0.1.1"
description = "A simple LaTeX generator for tables and images"
authors = [{ name = "Evgenij", email = "123@email.com" }]
dependencies = []