[project]
name = "nao_sql"
version = "2.2.5"
authors = [
    { name = "Noah Harris" }
]
description = "The point of this package is to streamline the interaction of mssql databases in Python."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

dependencies = [
    "requests>=2.24.0",
    "pyodbc>=5.0.1"
]
