# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nodens-gateway"
version = "25.3.0"
description = "Run the NodeNs gateway"
readme = "README.md"
authors = [{ name = "Khalid Z Rajab", email = "khalid@nodens.eu" }]
license = "MIT"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["nodens", "gateway", "radar"]
dependencies = [
    "paho-mqtt==1.6.1",
    'tomli; python_version < "3.11"',
    "pyyaml",
    "numpy",
    "platformdirs",
]
requires-python = ">=3.7"

[project.urls]
Homepage = "https://www.nodens.eu"

[project.scripts]
nodens-gateway = "nodens.gateway.__main__:main"