[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pdf-approval"
version = "0.1.1"
description = "Lightweight PDF approval testing library."
readme = "README.md"
license = {file = "LICENSE"}
authors = [
  { name = "Abderrahmen khalledi", email = "abderrahmen.khalledi@gmail.com" }
]
keywords = ["pdf", "testing", "approval-tests"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]
[project.urls]
Homepage = "https://github.com/Abderrahmen/pdf-approval"
Repository = "https://github.com/Abderrahmen/pdf-approval"