[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/htx"]

[project]
name = "htx"
version = "0.0.3"
authors = [
    { name="Example Author", email="author@example.com" },
]
description = "htx exchange api client"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = {text = "MIT"}

[project.urls]
Homepage = "https://github.com/ccxt/ccxt"
Issues = "https://github.com/ccxt/ccxt"
