[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "FMegaLib"
version = "0.0.1"
authors = [
 { name="Leonid", email="" },
]
description = ""
readme = "README.md"
requires-python = ">=3.10.0"
classifiers = [
   "Programming Language :: Python :: 3",
   "License :: OSI Approved :: MIT License",
   "Operating System :: OS Independent",
]