[tool.poetry]
name = "matchescu-reference-store"
version = "0.1.1"
description = "Storage options for entity references"
authors = ["Andrei Olar <andrei.olar@samlex.ro>"]
license = "MIT"
readme = "README.md"
packages = [{include="matchescu", from="src"}]

[tool.poetry.dependencies]
python = "^3.12"
matchescu-base = "^0.12.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
ruff = "^0.11.1"
mypy = "^1.15.0"
pytest = "^8.3.5"

