[build-system]
requires = ["setuptools", "wheel", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "rxnDB"
dynamic = ["version"]
description = "A Python Shiny app for reaction database management"
readme = "README.md"
requires-python = ">=3.13"
license = {text = "MIT"}
classifiers = [
    "Natural Language :: English",
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Visualization"
]
authors = [{ name = "Buchanan Kerswell", email = "buck.kerswell@gmail.com" }]
dependencies = [
    "shiny",
    "shinywidgets",
    "anywidget",
    "pandas",
    "plotly",
    "faicons"
]

[project.optional-dependencies]
dev = ["pytest", "pip"]
docs = [
    "sphinx<7.0",
    "sphinx-rtd-theme",
    "sphinx-autoapi",
    "sphinxcontrib-httpdomain"
]

[project.urls]
Repository = "https://github.com/buchanankerswell/kerswell_et_al_rxnDB"

[project.scripts]
rxndb = "rxnDB.cli:main"

[tool.setuptools]
license-files = ["LICENSE"]

[tool.setuptools.packages.find]
where = ["."]
include = ["rxnDB*"]

[tool.setuptools_scm]
