[tool.poetry]
name = "anydocs"
version = "0.1.0"
description = ""
authors = ["bahamondex <oscar.bahamonde@oscarbahamonde.awsapps.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
python-docx = "^1.1.2"
bs4 = "^0.0.2"
lxml = "^5.3.1"
requests = "^2.32.3"
cbase64 = "^0.0.9"
openpyxl = "^3.1.5"
python-pptx = "^1.0.2"
pypdf2 = "^3.0.1"
pymupdf = "^1.25.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
