[build-system]
requires = ["setuptools>=42", "wheel", "setuptools-scm[toml]>=6.0"]
build-backend = "setuptools.build_meta"

[project]
name = "minestudio"
version="1.1.2"
description = "A simple and efficient Minecraft Agent development kit for AI research."
dependencies = [
    "av==13.1.0",
    "opencv-python==4.10.0.84",
    "opencv-python-headless==4.10.0.84",
    "setuptools",
    "tqdm",
    "numpy",
    "requests",
    "ipython",
    "typing",
    "gym",
    "gym3",
    "gymnasium",
    "hydra_colorlog", 
    "hydra-core>=1.3.2",
    "lmdb",
    "wandb",
    "torch>=2.3.1",
    "lightning",
    "scipy",
    "rich",
    "coloredlogs",
    "daemoniker", 
    "lxml", 
    "cuda-python",
    "diskcache", 
    "albumentations", 
    "einops", 
    "timm",
    "transformers", 
    "Pyro4",
    "xmltodict",
    "pyrender==0.1.25",
    "pyglet",
    "imgui",
    "pyopengl",
    "ray",
    "minecraft_data==3.20.0",
    "absl-py",
    "dm-tree",
    "x_transformers==0.27.1"
]
authors = [
    {name="CraftJarvis", email="craftjarvis@outlook.com"}
]
requires-python = ">=3.10"

[tool.setuptools]
packages = ["minestudio"]
include-package-data = true

[tool.setuptools-scm]
version_scheme = "post-release"
local_scheme = "node-and-timestamp"
include = ".gitignore"


[tool.setuptools.dynamic]
readme = {file = "README.md"}

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
