[project]
name = "BluePyll"
version = "0.1.4"
description = "A Python library designed to control BlueStacks through ADB commands, enabling seamless automation and management of Android applications on a PC."
readme = "README.md"
authors = [
    { name = "IAmNo1Special", email = "ivmno1special@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "adb-shell>=0.4.4",
    "opencv-python>=4.11.0.86",
    "pillow>=11.1.0",
    "psutil>=7.0.0",
    "pyautogui>=0.9.54",
    "pywin32>=310",
]

[project.urls]
homepage = "https://github.com/IAmNo1Sepcial/BluePyll"
issues = "https://github.com/IAmNo1Sepcial/BluePyll/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"