name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - run: uv sync --all-extras --dev

      - name: Lint codebase
        run: uv run ruff check

      - name: Check formatting
        run: uv run ruff format --check

  types:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - run: uv sync --all-extras --dev

      - name: Check types
        run: uv run mypy .

  # Temporarily disabled until we mock the backend responses
  #tests:
  #  runs-on: ubuntu-latest
  #  permissions:
  #    contents: read
  #    issues: write
  #    pull-requests: write
  #  strategy:
  #    matrix:
  #      python-version:
  #        - "3.13"
  #  steps:
  #    - uses: actions/checkout@v4
  #    - uses: astral-sh/setup-uv@v5
  #      with:
  #        enable-cache: true
  #    - uses: actions/setup-python@v5
  #      with:
  #        python-version-file: "pyproject.toml"
  #
  #    - name: Run pytest
  #      run: uv run pytest --junitxml=pytest.xml --cov=completo --cov-report=xml:coverage.xml
  #    - name: Comment PR
  #      if: ${{ github.event_name == 'pull_request' }}
  #      uses: MishaKav/pytest-coverage-comment@main
  #      with:
  #        pytest-xml-coverage-path: ./coverage.xml
  #        junitxml-path: ./pytest.xml
  #        unique-id-for-comment: ${{ matrix.python-version }}
  #        title: Coverage (${{ matrix.python-version }})
  #        badge-title: Coverage (${{ matrix.python-version }})
