[project]
name = "elicito"
version = "0.1.1"
description = "A Python package for learning prior distributions based on expert knowledge"
authors = [
    { name = "Florence Bockting", email = "florence.bockting@tu-dortmund.de" },
]
requires-python = ">=3.9, <3.12"
dependencies = [
    "tqdm == 4.67.1",
    "numpy == 1.26.4",
    "tensorflow == 2.15.1",
    "tensorflow-probability == 0.23.0",
    "tensorflow-io-gcs-filesystem == 0.31.0",
    "joblib == 1.4.2",
]
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Typing :: Typed",
]

[project.license]
text = "Apache-2.0"

[project.urls]
Homepage = "https://elicito.readthedocs.io"
Documentation = "https://elicito.readthedocs.io"
Changelog = "https://elicito.readthedocs.io/en/stable/changelog"
Repository = "https://github.com/florence-bockting/elicito"
Issues = "https://github.com/florence-bockting/elicito/issues"

[project.optional-dependencies]
plots = [
    "matplotlib>=3.7.1",
    "seaborn==0.11",
]
pandas = [
    "pandas==2.2.3",
]
scipy = [
    "scipy==1.13.1",
]
full = [
    "elicito[plots]",
    "elicito[scipy]",
    "elicito[pandas]",
]
locked = [
    "absl-py==2.2.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "astunparse==1.6.3 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "attrs==24.3.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "cachetools==5.5.2 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "certifi==2024.12.14 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "charset-normalizer==3.4.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "cloudpickle==3.1.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "colorama==0.4.6 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "decorator==5.2.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "dm-tree==0.1.9 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "flatbuffers==25.2.10 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "gast==0.6.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "google-auth==2.38.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "google-auth-oauthlib==1.2.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "google-pasta==0.2.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "grpcio==1.71.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "h5py==3.13.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "idna==3.10 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "joblib==1.4.2 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "keras==2.15.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "libclang==18.1.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "markdown==3.7 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "markupsafe==3.0.2 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "ml-dtypes==0.3.2 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "numpy==1.26.4 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "oauthlib==3.2.2 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "opt-einsum==3.4.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "packaging==24.2 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "protobuf==4.25.6 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "pyasn1==0.6.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "pyasn1-modules==0.4.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "requests==2.32.3 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "requests-oauthlib==2.0.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "rsa==4.9 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "setuptools==75.6.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "six==1.17.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "tensorboard==2.15.2 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "tensorboard-data-server==0.7.2 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "tensorflow==2.15.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "tensorflow-estimator==2.15.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "tensorflow-io-gcs-filesystem==0.31.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "tensorflow-probability==0.23.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "termcolor==2.5.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "tqdm==4.67.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "typing-extensions==4.12.2 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "urllib3==2.3.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "werkzeug==3.1.3 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "wheel==0.45.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "wrapt==1.14.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
]
plots-locked = [
    "contourpy==1.3.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "cycler==0.12.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "fonttools==4.56.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "kiwisolver==1.4.8 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "matplotlib==3.10.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "numpy==1.26.4 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "packaging==24.2 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "pandas==2.2.3 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "pillow==11.1.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "pyparsing==3.2.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "python-dateutil==2.9.0.post0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "pytz==2025.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "scipy==1.13.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "seaborn==0.11.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "six==1.17.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "tzdata==2025.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
]
pandas-locked = [
    "numpy==1.26.4 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "pandas==2.2.3 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "python-dateutil==2.9.0.post0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "pytz==2025.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "six==1.17.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "tzdata==2025.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
]
scipy-locked = [
    "numpy==1.26.4 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "scipy==1.13.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
]
full-locked = [
    "contourpy==1.3.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "cycler==0.12.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "fonttools==4.56.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "kiwisolver==1.4.8 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "matplotlib==3.10.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "numpy==1.26.4 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "packaging==24.2 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "pandas==2.2.3 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "pillow==11.1.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "pyparsing==3.2.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "python-dateutil==2.9.0.post0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "pytz==2025.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "scipy==1.13.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "seaborn==0.11.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "six==1.17.0 ; python_version >= \"3.10\" and python_version < \"3.11\"",
    "tzdata==2025.1 ; python_version >= \"3.10\" and python_version < \"3.11\"",
]

[dependency-groups]
dev = [
    "liccheck==0.9.2",
    "mypy==1.14.0",
    "types-tensorflow>=2.18.0",
    "types-seaborn>=0.13.2",
    "types-tqdm>=4.67.0",
    "scipy-stubs>=1.14.1; python_full_version >= '3.10'",
    "joblib-stubs>=1.4.2",
    "pip==24.3.1",
    "pre-commit==4.0.1",
    "setuptools==75.6.0",
    "towncrier==24.8.0",
    "cfgv==3.4.0",
    "click==8.1.8",
    "colorama==0.4.6 ; sys_platform == 'win32'",
    "distlib==0.3.9",
    "filelock==3.16.1",
    "identify==2.6.5",
    "jinja2==3.1.5",
    "markupsafe==3.0.2",
    "mypy-extensions==1.0.0",
    "nodeenv==1.9.1",
    "platformdirs==4.3.6",
    "pyyaml==6.0.2",
    "semantic-version==2.10.0",
    "toml==0.10.2",
    "typing-extensions==4.12.2",
    "virtualenv==20.28.1",
]
docs = [
    "attrs==24.3.0",
    "mkdocs-autorefs==1.2.0",
    "mkdocs-gen-files==0.5.0",
    "mkdocs-literate-nav==0.6.1",
    "mkdocs-material==9.5.49",
    "mkdocs-section-index==0.3.9",
    "mkdocs==1.6.1",
    "mkdocstrings-python-xref==1.6.2",
    "mkdocstrings-python==1.13.0",
    "pymdown-extensions==10.13",
    "ruff==0.8.6",
    "babel==2.16.0",
    "certifi==2024.12.14",
    "charset-normalizer==3.4.1",
    "click==8.1.8",
    "colorama==0.4.6",
    "ghp-import==2.1.0",
    "griffe==1.5.4",
    "idna==3.10",
    "jinja2==3.1.5",
    "markdown==3.7",
    "markupsafe==3.0.2",
    "mergedeep==1.3.4",
    "mkdocs-get-deps==0.2.0",
    "mkdocs-material-extensions==1.3.1",
    "mkdocstrings==0.27.0",
    "packaging==24.2",
    "paginate==0.5.7",
    "pathspec==0.12.1",
    "platformdirs==4.3.6",
    "pygments==2.19.1",
    "python-dateutil==2.9.0.post0",
    "pyyaml-env-tag==0.1",
    "pyyaml==6.0.2",
    "regex==2024.11.6",
    "requests==2.32.3",
    "six==1.17.0",
    "urllib3==2.3.0",
    "watchdog==6.0.0",
]
tests-min = [
    "pytest==8.3.4",
    "colorama==0.4.6 ; sys_platform == 'win32'",
    "iniconfig==2.0.0",
    "packaging==24.2",
    "pluggy==1.5.0",
]
tests-full = [
    "pytest-cov==6.0.0",
    "colorama==0.4.6 ; sys_platform == 'win32'",
    "coverage==7.6.10",
    "iniconfig==2.0.0",
    "packaging==24.2",
    "pluggy==1.5.0",
    "pytest==8.3.4",
]
tests = [
    { include-group = "tests-min" },
    { include-group = "tests-full" },
]
all-dev = [
    { include-group = "dev" },
    { include-group = "docs" },
    { include-group = "tests" },
]

[build-system]
requires = [
    "pdm-backend",
    "pdm-build-locked",
]
build-backend = "pdm.backend"

[tool.pdm.build]
locked = true
includes = [
    "src/elicito",
    "LICENCE",
]

[tool.coverage.run]
source = [
    "src",
]
branch = true

[tool.coverage.report]
fail_under = 5
skip_empty = true
show_missing = true
exclude_also = [
    "if TYPE_CHECKING",
    "@overload",
    "\\.\\.\\.",
]

[tool.mypy]
strict = true
disallow_any_unimported = true
show_error_codes = true
show_error_context = true
warn_unreachable = true
follow_imports = "normal"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.ruff]
src = [
    "src",
]
target-version = "py39"
line-length = 88

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "D",
    "PL",
    "TRY",
    "NPY",
    "RUF",
    "UP",
    "S",
]
unfixable = [
    "PD002",
]
ignore = [
    "D200",
    "D400",
    "UP007",
]

[tool.ruff.lint.per-file-ignores]
"test*.py" = [
    "D",
    "S101",
    "PLR2004",
]
"docs/*" = [
    "D100",
    "E402",
    "S101",
]
"scripts/*" = [
    "S101",
]
"stubs/*" = [
    "PLR0913",
]

[tool.ruff.lint.isort]
known-first-party = [
    "src",
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
docstring-code-format = true

[tool.towncrier]
package = "elicito"
package_dir = "src"
filename = "docs/changelog.md"
directory = "changelog/"
title_format = "## Expert prior elicitation method {version} ({project_date})"
underlines = [
    "",
    "",
    "",
]
issue_format = "[#{issue}](https://github.com/florence-bockting/elicito/pull/{issue})"
type = [
    { directory = "breaking", name = "‚ö†Ô∏è Breaking Changes", showcontent = true },
    { directory = "deprecation", name = "üóëÔ∏è Deprecations", showcontent = true },
    { directory = "feature", name = "üÜï Features", showcontent = true },
    { directory = "improvement", name = "üéâ Improvements", showcontent = true },
    { directory = "fix", name = "üêõ Bug Fixes", showcontent = true },
    { directory = "docs", name = "üìö Improved Documentation", showcontent = true },
    { directory = "trivial", name = "üîß Trivial/Internal Changes", showcontent = false },
]

[tool.liccheck]
authorized_licenses = [
    "bsd",
    "bsd license",
    "BSD 3-Clause",
    "3-Clause BSD",
    "CC0",
    "apache",
    "apache 2.0",
    "apache software",
    "apache software license",
    "Apache License, Version 2.0",
    "CMU License (MIT-CMU)",
    "Historical Permission Notice and Disclaimer (HPND)",
    "isc",
    "isc license",
    "isc license (iscl)",
    "gnu lgpl",
    "lgpl with exceptions or zpl",
    "LGPLv2+",
    "GNU Lesser General Public License v2 (LGPLv2)",
    "GNU Lesser General Public License v2 or later (LGPLv2+)",
    "mit",
    "mit license",
    "Mozilla Public License 2.0 (MPL 2.0)",
    "python software foundation",
    "python software foundation license",
    "The Unlicense (Unlicense)",
    "zpl 2.1",
]
unauthorized_licenses = [
    "agpl",
    "gnu agpl",
    "gpl v3",
    "gplv3",
    "gpl v2",
    "gplv2",
    "gpl v1",
    "gplv1",
]
