[project]
name = "koreo-core"
version = "0.1.0"
description = "Type-safe and testable KRM Templates and Workflows."
authors = [
    { name = "Robert Kluin", email = "robert.kluin@realkinetic.com" },
    { name = "Eric Larssen", email = "eric.larssen@realkinetic.com" },
    { name = "Tyler Treat", email = "tyler-treat@realkinetic.com" },
]
dependencies = [
    "cel-python==0.2.0",
    "kopf==1.37.4",
    "PyYAML==6.0.2",
    "kr8s==0.20.6",
    "uvloop==0.21.0",
    "fastjsonschema==2.21.1",
]
requires-python = ">=3.13"
readme = "README.md"

[project.license]
text = "Apache-2.0"

[project.urls]
Homepage = "https://koreo.dev"

[project.optional-dependencies]
dev = [
    "black==25.1.0",
    "pytest==8.3.5",
    "pytest-cov==6.0.0",
]

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pytest.ini_options]
pythonpath = "src"
addopts = [
    "-v",
    "--import-mode=importlib",
    "--cov=src",
    "--cov-branch",
    "--cov-report=term-missing",
]
