[tool.poetry]
name = "funda-monitor"
version = "1.1.0"
description = "FundaMonitor provides the easiest way to monitor real estate data from Funda, the Dutch housing website. You can track houses either for sale or for rent, and access historical data from the past few years."
authors = ["Will Chien", "Wouter"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
pyyaml = ">=6.0,<7.0"
diot = ">=0.1.6,<0.2.0"
pandas = ">=2.2.0,<3.0.0"
numpy = ">=1.26.0,<2.0.0"
requests = ">=2.31.0,<3.0.0"
beautifulsoup4 = ">=4.12.0,<5.0.0"
tqdm = ">=4.66.0,<5.0.0"
setuptools = ">=69.0.0,<70.0.0"
python-dateutil = ">=2.8.2,<3.0.0"
lxml = ">=5.1.0,<6.0.0"
selenium = ">=4.18.0,<5.0.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=7.1.3,<7.2.0"
ruff = ">=0.4.8,<0.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
