[project]
name = "openevals"
version = "0.0.13"
license = {text = "MIT"}
description = "Open-source evaluators for LLM applications"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "langchain>=0.3.18",
    "langchain-openai>=0.3.6",
    "langsmith>=0.3.15",
    "rich>=13.9.4",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "openai>=1.61.1",
    "pyright>=1.1.396",
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.3",
    "ruff>=0.9.5",
]

[tool.setuptools.packages.find]
include = ["openevals*"]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = [
  "."
]
