[project]
name = "hardspheres-2d"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "eschmidt42", email = "11818904+eschmidt42@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "numpy>=2.2.4",
    "polars>=1.25.2",
    "scipy>=1.15.2",
    "seaborn>=0.13.2",
    "tqdm>=4.67.1",
]

[project.scripts]
hardspheres2d = "hardspheres_2d.cli:main"

[tool.maturin]
module-name = "hardspheres_2d._core"
python-packages = ["hardspheres_2d"]
python-source = "src"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[dependency-groups]
dev = [
    "ipywidgets>=8.1.5",
    "notebook>=7.3.3",
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
]
