[tool.poetry]
name = "shops_nocodb_updater"
version = "v1.0.0"
description = "Verifying telegram user token."
authors = ["Pavel Mulin <pavel@tg-shops.com>"]
readme = "README.md"

[tool.poetry.dependencies]
httpx = ">=0.23.0"
pydantic = ">=1.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"