[project]
name = "demo-uv"
version = "1.1.10"
description = "uv demo"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.2.3",
    "requests>=2.32.3",
]

[project.scripts]
demo-uv = "demo_uv.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
packages = ["demo_uv"]

[tool.hatch.build.targets.wheel]
packages = ["demo_uv"]

[tool.hatch.build.targets.sdist]
include = [
    "demo_uv",
    "pyproject.toml",
    "uv.lock",
    "README.md",
]

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple/"
publish-url = "https://upload.pypi.org/legacy/"
explicit = true

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]


