[tool.poetry]
name = "mcnpy"
version = "0.2.5"
description = ""
authors = ["Juan Antonio Monleon de la Lluvia <juanmonleon96@gmail.com>"]
license = "GNU General Public License v3.0"
homepage = "https://github.com/monleon96/MCNPy.git"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
matplotlib = "^3.10.0"
pandas = "^2.2.3"
xarray = "^2025.3.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
ipykernel = "^6.29.5"
plotly = "^6.0.0"
nbformat = "^5.10.4"
twine = "^6.1.0"

[tool.poetry.group.docs.dependencies]
sphinx = "^8.2.1"
myst-parser = "^4.0.1"
sphinx-autobuild = "^2024.10.3"
sphinx-rtd-theme = "^3.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
