[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "revenium-middleware-core"
version = "0.1.0"
description = "A Python library that provides core functionality to send AI metering data to Revenium."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "GNU Lesser General Public License v3 or later (LGPLv3+)"}
authors = [
  {name = "Revenium", email = "info@revenium.io"}
]
dependencies = [
  "revenium_metering"
]
keywords = ["revenium", "middleware", "logging", "token-usage", "metering"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)",
  "Operating System :: OS Independent",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Libraries :: Python Modules"
]

[project.urls]
"Homepage" = "https://github.com/revenium/revenium-middleware-core-python"
"Bug Tracker" = "https://github.com/revenium/revenium-middleware-core-python/issues"
"Documentation" = "https://github.com/revenium/revenium-middleware-core-python/blob/main/README.md"

[project.optional-dependencies]
dev = [
  "pytest>=7.0.0",
  "pytest-cov",
  "flake8",
  "black",
  "mypy",
  "freezegun"
]
